@{
    ActivityName             = "NVTT Exporting"
    ErrorAutoDiscoveryFailed = "Auto-discovery of NVTT failed (registry/PATH variable)."
    ErrorExporterNotFound    = "Error: NVTT Exporter not found at: {0}"
    ErrorPresetNotFound      = "Error: No .dpf preset found in {0}."
    WarningNoFiles           = "No files matching '{0}' found."
    StartMessage             = "Starting export of {0} files (Preset: {1})..."
    WarningPrefix            = "WARNING: {0}"
    WarningExitCode          = "(Exit Code: {0})"
    WarningDetails           = "`nDetails: {0}"
    ItemDone                 = "[DONE] {0} -> {1}"
    ProgressPreparing        = "Preparing: 0 / {0}"
    ErrorFailedStart         = "Failed to start: {0}"
    ProgressStatus           = "Completed: {0} of {1} | Active background NVTT processes: {2}/{3}"
    ScriptAborted            = "`n[INTERRUPT] SCRIPT ABORTED VIA CTRL+C."
    KilledProcesses          = "Killed {0} background NVTT processes. Possible unfinished files:"
    KilledFileItem           = "{0}"
    ExportFinishedWithErrors = "`nExport finished. Success: {0} | Errors: {1}."
    ExportFinishedSuccess    = "`nSuccess! Exported {0} files without any errors."
}