@{
    ActivityName             = "NVTT-Export"
    ErrorAutoDiscoveryFailed = "Automatische Erkennung von NVTT fehlgeschlagen (Registrierung/PATH-Variable)."
    ErrorExporterNotFound    = "Fehler: NVTT Exporter nicht gefunden unter: {0}"
    ErrorPresetNotFound      = "Fehler: Keine .dpf-Voreinstellung in {0} gefunden."
    WarningNoFiles           = "Keine passenden Dateien für '{0}' gefunden."
    StartMessage             = "Starte Export von {0} Dateien (Preset: {1})..."
    WarningPrefix            = "WARNUNG: {0}"
    WarningExitCode          = "(Exit-Code: {0})"
    WarningDetails           = "`nDetails: {0}"
    ItemDone                 = "[FERTIG] {0} -> {1}"
    ProgressPreparing        = "Vorbereitung: 0 / {0}"
    ErrorFailedStart         = "Fehler beim Starten: {0}"
    ProgressStatus           = "Abgeschlossen: {0} von {1} | Aktive NVTT-Hintergrundprozesse: {2}/{3}"
    ScriptAborted            = "`n[UNTERBRECHUNG] SKRIPT ÜBER STRG+C ABGEBROCHEN."
    KilledProcesses          = "{0} NVTT-Hintergrundprozesse beendet. Mögliche unvollständige Dateien:"
    KilledFileItem           = "{0}"
    ExportFinishedWithErrors = "`nExport abgeschlossen. Erfolgreich: {0} | Fehler: {1}."
    ExportFinishedSuccess    = "`nErfolg! {0} Dateien ohne Fehler exportiert."
}