@{
    ActivityName             = "Eksport NVTT"
    ErrorAutoDiscoveryFailed = "Automatyczne wykrywanie NVTT nieudane (rejestr/zmienna PATH)"
    ErrorExporterNotFound    = "Błąd: Narzędzie NVTT nie zostało znalezione: {0}"
    ErrorPresetNotFound      = "Błąd: Nie znaleziono pliku .dpf w {0}."
    WarningNoFiles           = "Brak plików '{0}' do przetworzenia."
    StartMessage             = "Rozpoczęto eksport {0} plików (Profil: {1})..."
    WarningPrefix            = "UWAGA: {0}"
    WarningExitCode          = "(Kod wyjścia: {0})"
    WarningDetails           = "`nSzczegóły: {0}"
    ItemDone                 = "[GOTOWE] {0} -> {1}"
    ProgressPreparing        = "Przygotowywanie: 0 / {0}"
    ErrorFailedStart         = "Nie udało sie rozpocząć: {0}"
    ProgressStatus           = "Zakończono: {0} z {1} | Aktywne procesy NVTT w tle: {2}/{3}"
    ScriptAborted            = "`n[INTERRUPT] PRZERWANO SKRYPT ZA POMOCĄ CTRL+C."
    KilledProcesses          = "Zakończono {0} procesów NVTT w tle. Możliwe nieukończone pliki:"
    KilledFileItem           = "{0}"
    ExportFinishedWithErrors = "`nEksport zakończony. Sukces: {0} | Błędy: {1}."
    ExportFinishedSuccess    = "`nSukces! Wyeksportowano {0} plików bez żadnych błędów."
}