@{
    ActivityName             = "Exportation NVTT"
    ErrorAutoDiscoveryFailed = "Échec de la détection automatique de NVTT (registre/variable PATH)."
    ErrorExporterNotFound    = "Erreur : NVTT Exporter introuvable à : {0}"
    ErrorPresetNotFound      = "Erreur : Aucun profil .dpf trouvé dans {0}."
    WarningNoFiles           = "Aucun fichier correspondant à '{0}' trouvé."
    StartMessage             = "Démarrage de l'exportation de {0} fichiers (Profil : {1})..."
    WarningPrefix            = "AVERTISSEMENT : {0}"
    WarningExitCode          = "(Code de sortie : {0})"
    WarningDetails           = "`nDétails : {0}"
    ItemDone                 = "[TERMINÉ] {0} -> {1}"
    ProgressPreparing        = "Préparation : 0 / {0}"
    ErrorFailedStart         = "Échec du démarrage : {0}"
    ProgressStatus           = "Terminé : {0} sur {1} | Processus NVTT actifs en arrière-plan : {2}/{3}"
    ScriptAborted            = "`n[INTERRUPTION] SCRIPT ANNULÉ VIA CTRL+C."
    KilledProcesses          = "{0} processus NVTT en arrière-plan arrêtés. Fichiers potentiellement inachevés :"
    KilledFileItem           = "{0}"
    ExportFinishedWithErrors = "`nExportation terminée. Succès : {0} | Erreurs : {1}."
    ExportFinishedSuccess    = "`nSuccès ! {0} fichiers exportés sans aucune erreur."
}